spring.application.name=Santa
spring.datasource.url=${santa_sql_conn}
spring.datasource.username=${santa_sql_user}
spring.datasource.password=${santa_sql_password}
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto = update
server.port=8085

